name: build-maven-and-push-image
on: push
jobs:
  build-maven-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_JSON }}
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - run: mvn --batch-mode verify -T 1C -Dparallel=all -DperCoreThreadCount=true jib:build -Djib.to.image="europe-west1-docker.pkg.dev/tagbevakning/test/${{ github.event.repository.name }}:${{ github.sha }}"
